# ===================================
#  List Behavior Config
# ===================================

title: indikator.photography::lang.menu.categories
list: ~/plugins/indikator/photography/models/categories/columns.yaml

modelClass: Indikator\Photography\Models\Categories
recordUrl: indikator/photography/categories/update/:id
noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 15
showCheckboxes: true
showSetup: true

defaultSort:
    column: name
    direction: asc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
