# ===================================
#  List Behavior Config
# ===================================

title: indikator.photography::lang.menu.photos
list: ~/plugins/indikator/photography/models/photos/columns.yaml

modelClass: Indikator\Photography\Models\Photos
recordUrl: indikator/photography/photos/update/:id
noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 15
showCheckboxes: true
showSetup: true

defaultSort:
    column: exif_date
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
