# ===================================
#  List Behavior Config
# ===================================

title: indikator.photography::lang.menu.equipment
list: ~/plugins/indikator/photography/models/equipment/columns.yaml

modelClass: Indikator\Photography\Models\Equipment
recordUrl: indikator/photography/equipment/update/:id
noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 15
showCheckboxes: true
showSetup: true

defaultSort:
    column: name
    direction: asc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
